[build]
  publish = ""
  command = "npm run deploy"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
  [[redirects]]
from = '/_next/image/*'
query = { q = ':quality', url = ':url', w = ':width' }
to = '/.netlify/images?url=:url&w=:width&q=:quality'
status = 200
force = true